Smart charging
rongxinyin/ev-infrastructure-tool pull request #33
Opened 2024-09-25 18:29 UTC by leongmichael

2024-09-25 22:06 UTC, leongmichael commented
![image](https://github.com/user-attachments/assets/6979e42f-9941-45bb-b24e-70efe75f209c)
![image](https://github.com/user-attachments/assets/68dca343-5358-41bf-b741-488becf28d3f)

2024-09-27 01:19 UTC, rongxinyin requested changes
testing data path that should work for different os systems.

2024-09-27 01:19 UTC, rongxinyin commented on server/python-backend/scripts/post-process/smart-charging-analysis.py
> +    base_dir = os.getcwd() + "\\python-backend\\tests"
base dir path should work for all os systems.

2024-09-27 01:28 UTC, rongxinyin commented on server/python-backend/scripts/post-process/smart-charging-analysis.py
> +    base_dir = os.getcwd() + "\\python-backend\\tests"
fix the base dir using a relative path.

2024-09-27 01:28 UTC, merged